apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: victoria-metrics-k8s-stack
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.76.0
    releaseName: vm-stack
    namespace: victoria-metrics
    valuesFile: vm-stack-values.yaml
  - name: victoria-logs-single
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.12.4
    releaseName: victoria-logs
    namespace: victoria-metrics
    valuesFile: victoria-logs-values.yaml
  - name: victoria-traces-single
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.0.7
    releaseName: victoria-traces
    namespace: victoria-metrics
    valuesFile: victoria-traces-values.yaml
