server:
  retentionPeriod: 7d
  resources:
    requests:
      cpu: 30m
      memory: 40Mi
    limits:
      cpu: 300m
      memory: 100Mi
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    search.maxConcurrentRequests: "4"
    search.maxMemoryPerQuery: 20MB
  persistentVolume:
    enabled: true
    size: 3Gi
    accessModes:
      - ReadWriteOnce
