apiVersion: v1
kind: ConfigMap
metadata:
  name: nowchess-env-config
data:
  QUARKUS_PROFILE: deployed
  CORS_ORIGINS: ""
  NOWCHESS_COORDINATOR_ENABLED: "true"
  REDIS_PREFIX: nowchess-staging
  QUARKUS_LOG_LEVEL: "INFO"
  NOWCHESS_COORDINATOR_SCALE_MIN_REPLICAS: "2"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://grafana-k8s-monitoring-alloy-receiver.monitoring.svc.cluster.local:4317"
