apiVersion: v1
kind: ConfigMap
metadata:
  name: nowchess-env-config
data:
  QUARKUS_PROFILE: deployed
  CORS_ORIGINS: ""
  NOWCHESS_COORDINATOR_ENABLED: "true"
  REDIS_PREFIX: nowchess-staging
  QUARKUS_LOG_LEVEL: "INFO"
