apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: sealed-secrets
      targetRevision: 2.5.19
      helm:
        valueFiles:
          - $values/sealed-secrets/eu-central-1/values.yaml
    - repoURL: git@git.janis-eccarius.de:NowChess/GitOps.git
      path: ./sealed-secrets/eu-central-1
      ref: values
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
