apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - orch-project.yaml
  - orch-projectconfig.yaml
  - orch-warehouse.yaml
  - orch-stage.yaml
  - orch-promotion-template.yaml