apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: orchestration-kargo
spec:
  promotionPolicies:
    - autoPromotionEnabled: true
      stageSelector:
        name: regex:^.*$