apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.15.1
      helm:
        valueFiles:
          - $values/ingress-nginx/eu-central-1/values.yaml
    - repoURL: git@git.janis-eccarius.de:NowChess/GitOps.git
      path: ./ingress-nginx/eu-central-1
      ref: values
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
