apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nowchess-staging
resources:
- ../base
- ingress.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: nowchess-env-config
    data:
      QUARKUS_PROFILE: deployed
      CORS_ORIGINS: https://st.nowchess.janis-eccarius.de
      NOWCHESS_COORDINATOR_ENABLED: "true"
      REDIS_PREFIX: nowchess-staging
      QUARKUS_LOG_LEVEL: "INFO"
  target:
    kind: ConfigMap
    name: nowchess-env-config
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    metadata:
      name: nowchess-account
    spec:
      replicas: 1
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    metadata:
      name: nowchess-core
    spec:
      replicas: 1
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    metadata:
      name: nowchess-ws
    spec:
      replicas: 1
images:
- name: ghcr.io/now-chess/now-chess-systems/account
  newTag: 0.3.0
- name: ghcr.io/now-chess/now-chess-systems/bot-platform
  newTag: 0.4.0
- name: ghcr.io/now-chess/now-chess-systems/coordinator
  newTag: 0.4.0
- name: ghcr.io/now-chess/now-chess-systems/core
  newTag: 0.24.0
- name: ghcr.io/now-chess/now-chess-systems/io
  newTag: 0.16.0
- name: ghcr.io/now-chess/now-chess-systems/official-bots
  newTag: 0.4.0
- name: ghcr.io/now-chess/now-chess-systems/rule
  newTag: 0.13.0
- name: ghcr.io/now-chess/now-chess-systems/store
  newTag: 0.3.0
- name: ghcr.io/now-chess/now-chess-systems/ws
  newTag: 0.4.0
configurations:
- rollout-transform.yaml
openapi:
  path: argo_all_k8s_kustomize_schema.json
