apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nowchess-staging
resources:
- ../base
- ingress.yaml
- rbac-coordinator.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: nowchess-env-config
    data:
      QUARKUS_PROFILE: deployed
      CORS_ORIGINS: https://st.nowchess.janis-eccarius.de
      NOWCHESS_COORDINATOR_ENABLED: "true"
      NOWCHESS_COORDINATOR_SCALE_MIN_REPLICAS: "1"
      REDIS_PREFIX: nowchess-staging
      QUARKUS_LOG_LEVEL: "INFO"
  target:
    kind: ConfigMap
    name: nowchess-env-config
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: nowchess-analysis
    spec:
      maxReplicas: 1
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: nowchess-account
    spec:
      minReplicas: 1
      maxReplicas: 1
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: nowchess-ws
    spec:
      minReplicas: 1
      maxReplicas: 1
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: nowchess-bot-platform
    spec:
      maxReplicas: 1
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: nowchess-io
    spec:
      maxReplicas: 1
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: nowchess-official-bots
    spec:
      maxReplicas: 1
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: nowchess-rule
    spec:
      maxReplicas: 1
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: nowchess-store
    spec:
      maxReplicas: 1
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: nowchess-tournament
    spec:
      maxReplicas: 1
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    metadata:
      name: nowchess-core
    spec:
      replicas: 1
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    metadata:
      name: nowchess-official-bots
    spec:
      template:
        spec:
          containers:
            - name: nowchess-official-bots
              env:
                - name: QUARKUS_LOG_CATEGORY__IO_SMALLRYE_JWT__LEVEL
                  value: DEBUG
                - name: QUARKUS_LOG_CATEGORY__IO_QUARKUS_SECURITY__LEVEL
                  value: DEBUG
images:
- name: ghcr.io/now-chess/now-chess-systems/account
  newTag: 0.26.0
- name: ghcr.io/now-chess/now-chess-systems/analysis
  newTag: 0.2.0
- name: ghcr.io/now-chess/now-chess-systems/bot-platform
  newTag: 0.12.0
- name: ghcr.io/now-chess/now-chess-systems/coordinator
  newTag: 0.32.0
- name: ghcr.io/now-chess/now-chess-systems/core
  newTag: 0.53.0
- name: ghcr.io/now-chess/now-chess-systems/frontend
  newTag: 0.6.3
- name: ghcr.io/now-chess/now-chess-systems/io
  newTag: 0.23.0
- name: ghcr.io/now-chess/now-chess-systems/official-bots
  newTag: 0.34.0
- name: ghcr.io/now-chess/now-chess-systems/rule
  newTag: 0.18.0
- name: ghcr.io/now-chess/now-chess-systems/store
  newTag: 0.24.0
- name: ghcr.io/now-chess/now-chess-systems/tournament
  newTag: 0.9.0
- name: ghcr.io/now-chess/now-chess-systems/ws
  newTag: 0.17.0
configurations:
- rollout-transform.yaml
openapi:
  path: argo_all_k8s_kustomize_schema.json
