apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../eu-central-1
# Patch SSH_HOST if the postgres server is different for htwg-1:
# patches:
#   - patch: |-
#       apiVersion: v1
#       kind: ConfigMap
#       metadata:
#         name: postgres-tunnel-config
#         namespace: postgres-tunnel
#       data:
#         SSH_HOST: "<htwg-1-postgres-host>"
#     target:
#       kind: ConfigMap
#       name: postgres-tunnel-config
