apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  destination:
    namespace: victoria-metrics
    server: https://kubernetes.default.svc
  sources:
    - repoURL: git@git.janis-eccarius.de:NowChess/GitOps.git
      path: ./victoria-metrics/eu-central-1
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
