apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-traces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    namespace: victoria-metrics
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-traces-single
      targetRevision: 0.0.7
      helm:
        valueFiles:
          - $values/victoria-metrics/eu-central-1/victoria-traces-values.yaml
    - repoURL: git@git.janis-eccarius.de:NowChess/GitOps.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
