architecture: standalone

auth:
  enabled: false

global:
  security:
    allowInsecureImages: true

image:
  registry: quay.io
  repository: redis/redis
  tag: "7-alpine"

master:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  persistence:
    enabled: false
