---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ncs-internal-secret
  namespace: nowchess
spec:
  encryptedData:
    INTERNAL_SECRET: AgAtyRSkLOrIJjXZioKxzbJH0pZHHUHNaTYeIQ6wtYhIk8h67rZ6KCG1V5hOPgzQ5QBSVmrSjk+rwg1bd8AkCtV4sOVUd5Yq304+/deZjNR20wn4qyS9uUPAcj4bLYzYezewvqYiQkBEy1eiWVX4VIMN9K4wIH8A8D4ABKRaGB8G+prlNg8pfMl4GFmp9gTfkiOc6bKTTMevSinapqUrN77ihhmi9gfpkdQF6B2xITBuG9ZWZ7NHccrQvm/HPXsphIap3wUcfXfuKnDY6q0PVhGz2dgtjETMK9q2L6ANL4+DpLeOXM94m3rSEum+DUaKwjYt6icZGPqVBmePv+3N7aYt4BjG1JPmWTxcPwBz3A3/OBp+oajBnXyw+Mryov5L2dTyl/Wmc0YJqev+KoZ3X+7/hE0PhJsNY5YazJ2uPrKBcvBjV4FFTbRAflqtSnzhqsViDMqUON6rDWc/woUaOT6n696Tpu5JgBBV6IDx78RYo42mzX7UQbIiLXampSX16dBAEPNp8ipQ7Z9PTFNz+utqUL+aftjuPs12UKImfWwu3TaKZLS6ZSqMJBwU1dMZK24XWb+PKrNz9dZzTNuC7lEUfqe2ffpHJbW3VcgAIr2dcwRSmzeqllhUY6fIHDMR+tbVNjSMTE4yler2xDSNShcAHoWF/VmGx/WVr2fLmjV/+pv1N2GY3UohGTsZHq5FwO85Y8bwCF/nAY9++Udf51Qrx6+5kXh5q54mPJcI03Tmgw==
  template:
    metadata:
      name: ncs-internal-secret
      namespace: nowchess
