---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ncs-internal-secret
  namespace: nowchess
spec:
  encryptedData:
    INTERNAL_SECRET: AgCP9Hta5o9u+6PBS2u+mTk/xNbqY/5IUGUVymUERUCm4fpHPKc/fAo44/cxkYe0BghhjJOw3sdf6JIuP9W4USieCN1Tf9UIRjp2/e1kGUivA5bcasI/pJDdQ+zEir230oAI+hAAyXOQtBhTfqLn6uljk8d9wL72fwa3wnZhM4kSMIqt/ByD6Xtxb1nIN4ei+g6TUJwoMYos8j4UPIAVAQ++HwX0Fcrr0dEHa/dFtkfKVqliuM7JlB3VPMPOfBoxqYNQvZl0gfy6h34fRrk3py0x+uQO9LiCA5Kc4imnMq4tZoDucFCt/D0IkyvQ+K3dU+VIJXbZ2NsRX5fLqGyEYUTNldGKHW12xPPY50ADbnNDYDvEWgb78zFCfYBjsNhTOdYYUNlJs49y9jkOAhZ9EZm/VfBDEFqVN3CvrcQAnrOjJaHdqh7BjIpjgjfmTLO1fVdwwodUSD9EVEZyiB50kNPzZCHJ6+iCVjZOmrg2SKIM87r63BOyj3NkOCJeab5kbe/Nx/EFE1IRPcd+eXzSQNS06iQsjMx85YaF0zEBsR/KU2D9wH92vLxIwPur4yukt0YHUX4kUncptdGAoUKu/lWoQG4jk1f0+FsyCUQVh4IBLxxx9v3nUeZ4vfV0t2+Pp133kae9cDecLAVb/n6VNQnwNrWRPHgZRDFG7vUEL+xcXBmZf1u8cp7AofSzaN9+m2EZdnkMN5fN74jBWlxYSt8p+Sr7tZ6C20n9rlG33A2AuA==
  template:
    metadata:
      name: ncs-internal-secret
      namespace: nowchess
