---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ncs-tournament-bot-secret
  namespace: nowchess
spec:
  encryptedData:
    TOURNAMENT_BOT_TOKEN: AgBeVXB71v/88ksndl+bn4k8niG7rlKCDxWEinMgxh0vqLjtB/BWwwhhRp7064/jFH7Qt02nb9TF8N4+GIiBNykIGQLQtUBzvMp7I7EGSAHNsFSlXFTURQQJo5+C8L/H9c0UDQ+gunqCinz2mEZw1LlnMgQEqfMN3RCVK9YtW6f76jk3WLpet4g082lfy9cou2FZ+AgQq3zSBf6//OmlqrKRLkve1Nbxy4dS2IAvfLd/OdiC29sFs41nk3TFyrR9jPg8P4cYfd99O9XhabKRrCR8J1TxovCiWWQVBI+E1mmbQW5d6pcw1qO2fYsRGvdVb7DB+IiV3WjMHO6U3T/TV8sHhhAUSMELtD0NIfXyphkevK7Mtd3wPHgk6U2vTpNH3kionywff8jBeM8xWmTCOnHgRlCRoUrigysbAKNwGKjqEdWM3En8qKf4o6aTxFoQODIa09esivqcXs6U7WzqXWxjrZDVwsjauzC+eUyvJQv+yDPHSMjUt35r/CZF9xuOtRPG0ZmKmO6yAlbgLBnSYiOeEa9xPxhh3n7+kV9TijHgnxcsGhfzpxzQLJ49g7TPkSqudC+wZtMKt719HrW3SPiUnIT521ntqvaBGc+O8+AA1lEB5OaIfN1yKjUZmy7zPZhHG7wtTVBaXisXV0qdw62/V9aejgClb2S7OvXx7tuA4hrwKMXNyZ+YlN+10g6mIaxD62naiWRbrXdKy1dpgqtqq4erOUdGX09twWJ1kUWb0azUNV6BJTUinyTjh8bzbdq3cJ+IYm8gSe8QovAe9vpwAt9rRGTE8+lHBzUcEzQZwNQfK8FqqvHa2wDbFTaVt5G6wVNtGb2DLvlcIMKe5zSads0W0rwKXEKl2YUvZtBdVkdQvJD3/GlC4zBa7/TmIqCj
  template:
    metadata:
      name: ncs-tournament-bot-secret
      namespace: nowchess
