---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgApDWti3f39LPRyc0kDEQDopNzTT+emqJqulZilTDcxrI56YylKNhCglZvJeBKyhMXwvrK9nVe7gVEG6Zgs4HmaB6HOXTnAJFyyEmkDfA0vtJA35cy76gjCu5F7ctxnYJs0ZODxrfi5NhvdFCYKKEzPsH0Qf3NZY0VVjjavjdGolZaenwoLylV/h00VWhB0TdBU8tH88YTljQjRbgOXht5535k7W1n1ecEORB968gT+PASYiDaCNgxyK+hSkxpYb1OZlhLJnfa61xYTIunAB9Fkm6PZrdDLbBHnR4fB5+oAaG41UvWclGulkDb/YuLIqfpQi8g4Q6p8XixwF9ajy/txw9qtdBaPPeFHRC9WuQX4jtCc7O6H6V/y3qcCiWGNXy56fy/KAVU/UkLtnU0dlN9Wm9/6+luA2cE+vPQRrIAp/iGgV8p3Ck13Kof83X1qA1qvyxxycSS1j8mep6snCLmYGSAn8lxzCaZfv+kwLMAuH6x61mEB7V6RgTke/PEbGgQ73RtLI0tBPeuideLQ+bpzusqS+AE2KDTtuaQ4JPl708s4KMVy+Jueo5Sjaf49FD4EPaEY7cno8AwaQmBuCSvwzjVOkF0stXYLBLeaLMs2RxQj9IK7ua2iUEI58/BJ6TKE4gw2tLe5jFB9M8lf5dVGci3skWevhBd0DF2vLyFejWyaJ3kBn0yxjmHSE8BnCRTTFSHtpmkUprBaMTCjK28v7AsDRPbgFF8jcl6uIu+yVA==
  template:
    metadata:
      name: postgres-credentials
      namespace: postgres
