apiVersion: v1
kind: Secret
metadata:
  name: ncs-db-secrets
  namespace: nowchess
type: Opaque
stringData:
  ACCOUNT_DB_USER: ""
  ACCOUNT_DB_PASSWORD: ""
  ACCOUNT_DB_URL: ""
  STORE_DB_USER: ""
  STORE_DB_PASSWORD: ""
  STORE_DB_URL: ""
