apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nowchess-staging
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: nowchess-kargo:staging
spec:
  project: default
  destination:
    namespace: nowchess-staging
    server: https://kubernetes.default.svc
  sources:
    - repoURL: git@git.janis-eccarius.de:NowChess/Gitops.git
      path: ./nowchess/eu-central-1-staging
      ref: values
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
