apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nowchess
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: nowchess-kargo:eu-central-1-prod
spec:
  project: default
  destination:
    namespace: nowchess
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      name: nowchess-core
      jsonPointers:
        - /spec/replicas
  sources:
    - repoURL: git@git.janis-eccarius.de:NowChess/Gitops.git
      path: ./nowchess/eu-central-1-prod
      ref: values
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
