apiVersion: v1
kind: Secret
metadata:
  name: git-kargo-secret
  namespace: nowchess-kargo
  labels:
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  repoURL: https://git.janis-eccarius.de/NowChess/Gitops.git
  repoURLIsRegex: "false"
  username: ""
  password: ""
