apiVersion: v1
kind: Secret
metadata:
  name: gitea
  namespace: nowchess-kargo
  labels:
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  repoURL: https://git.janis-eccarius.de/NowChess/Gitops.git
  username: ""
  password: ""
