---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github
  namespace: redis
spec:
  encryptedData:
    .dockerconfigjson: AgA9QA+qeRfGX0tWO0+Z5ewG8BrWOmwZriXR9h3hPWI1L0N5nFWBRZpqyPQqe0+G/hvCdTRmaplUh3tthTymOT0QYhtRGOpOBPn2Yn+F9X+J3lKptH2Lg+vNsY1An14y9HqFv/dP4ljZIf1qGtmMHtyeweXylYKLmq391GpCJ89x8rcdVFks8lu40euMsHtpG1IrMyQgxicE6HdDDouu22CnixrF/ywasS15g3epW0uSpTOhJGMpURjkxSIEegajFU/q3j20fJRrymoRt0UsQwtg9YwsaDEnF/hnQEChhFDx1RfIgQOex79urk7cZvlIZjjcZeRdtiC1wCybW57JE+bZUbUAaMN7aZNQKHWgLClA/DnWauuJuDe1DCjH8UmXnivQb5VFLmJJwp0Ydf13yZ66z8dnLZMYGjS1C6aPx2QrW6siGyKG9kX8IixsV+MqFOF7vGyQyBTs8R084OjGi+NzwX4lYP5cD1xVQ51GhpcmF0XHdgBewHGV34KK9fiR20FWHt0oCLnx67PSXn2f/26B2V+D5q/vr2Fs/5ftYeUr34h9pNCUv677UAOKycEo91paAlrniVjtrO1oyUdRQKuMqUQR9O9PAoqv6u/EmExKjJHUSJJW6LbxxYGkGehvpLAushh5/UMRH23b2fZZLZ3Og5f27eRx/CgvNb1I6ngOjfqAJIHx1yxKD2eJUNqAr0xHCr4y0qMu7ixT1VwJbHAFWKO3u4LtrycPBEczgyRHV9C/6dMyinKCHaMQvnk/H6SjS44cWvo40i/y534zXgjfvSg58aww1dehAgp8OgcOLIUSObli1NE2aMq/FwYM+E64LQcPP4TIpuc8tQtrebfOBq8ocwu3m1FRhMWNU5Zt9f5BlnTy4jOiVPARZyuhsS4tRZ3Q13DsRlGHcY3Ozr3lGBBFR2qXNLJ2nd9kDDjJkzcHC6p4hhJIB0qukv3cEl9ZbGIGIc4Qcjv3Og==
  template:
    metadata:
      name: github
      namespace: redis
    type: kubernetes.io/dockerconfigjson
