---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github
  namespace: redis
spec:
  encryptedData:
    .dockerconfigjson: AgCSJhLahqRotAO5LNWhogySyDUmvgyCKNI2Qh40fxiK3UMHf0NvHEUjNF2ow7SVc/oQxK+JiRP1SAa1V/XSTIKTwU/iPBfhASCKbh48EsugGlO0QYxjZGitwrDtt6VFutKLWm/NO6nhoLKsNBgltPkKUN/7nVXgk+e7aBQFFYEzDBN1592ZMWT1Z699/dMaK6eRtmn0S3UfYONaFcngPcp02UGv7zCtNxCWSVx0wCu0ZgBocZDco3dcH3Voai93sK1zfEAx32QSSi+588rB8ca74RQq0GuziZz2iJriDXp8/iZSwpxBC3M3IizdcLGSA3zcvtQ/1fYIJ36KtXziFQ+lZxtdAUQzXPSreFWUREARG2TQE2TIbd3owHEydM6W04JULEqaDTQ7hu54+JD9xTfaUVV7kHVpmNqU1wD8l5+qFNemQwupJ8NBFCGFqmVrUkDJujFi6qV0bOy3vCT4VA1iOQ/GMflxQu1X6ma1MOq8H6mkaKohYw8kg+CqHMRw5L0vsPFsd2rJelc+o4O2+RShk9Z3vSuw38ahoSI/JDaIfBlb2RvK/bNndOxCF2G4/O0OJ0MOjLm/jn4K7837mskS99nAh36tNLS1o4kv3asjoGS2x1J++d5VhFzxFjO++lreErXRg4BQv34QRBvppqqrM2KxYMlLFJBgTLsi0sIr5n2Rqd8qzPXOnE2XNo7Il1eAA713iEZMXSkiEd2g5n9wH1FMSHfbrzTFOsUPjVPIvN5OYF4I+RygLbI2slxJ0Va3YsWKy1xUm/T401SF3DIQOLbwCn3AAaSgtKyWEfDcrCELCOmOd5zWTIR3+OcWR/x0s4AxtTEuXx5G/h+N0ZegXzY+qhWALX8YVd/u9yz3KXTf41NZXnN+9W8vzkXcBD+v6+NH24agSWJzJhZHcKjSXMLjcWFY8hMITbWpSPTxGthWZK26HAYK5fc0Dpk9WYydci4wyDF4q2v10w==
  template:
    metadata:
      name: github
      namespace: redis
    type: kubernetes.io/dockerconfigjson
