---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-tunnel-ssh-key
  namespace: postgres-tunnel
spec:
  encryptedData:
    id_rsa: AgCSBvpowfH8Uq1yLjwfvDmupNkOliyzFrPUM8T+qEVNzS+OBEs1Qv5OlilmVMfQeJGY0ljAKvd3C9xCbH06n14Kh5vmMlw1ExnPjfjPwunJ2rPqxMLGV1iJBjq0Y3ezsoXjSbQVyVdlKfcK4BtIzk7AEEhKIn78BInu0jJ98MiuRx79dpY8VWIm1R9fBVcIeUXUdRspTCsjoXpyDICTA7AOG8xBZjGxpyc4XnDEhtgT1/7wxELggrl2GeLe1xihDOsDKdQ063T+UOxR0Hbodzqc7SWpRY1hNrfSNIeecBVsyrFwjjwrkUsvRHD8krVX805wH0QUH2O3lW+myRuBgrISg/AaHkpDY/Xnty+XGKty1PngMRGRY3DDFEshlfS1mn20PORMR2+ylTf91SS02t2lBPjT0ipmzWaRpxltQg5mRAEjEYEPst+WU4SuqnTOym5/cM8z7kOkzdQyXaatW1ZLDz9BcTp8zGGfvQUtYkDPGm8G3K5qjJ3ska9Ag2uvwRrXv/gKG2SnzOjfvsM1qhlQoz0lDRtt8w1gdg1roKEter0XnZbM080sn9T59guO4+nfMl/FtBJVTq0sa9ALBWYosCkyF72rQVee7R+xP+vK6y4khYA3mIlMz6AaC6/IjP43+N1CWEHwTSpn56gBMstkMIR+AfK/hgmp5apepaeIg37USUABp+VOaA8W49yuPRB32vLqD9PIa/9jYqG4lCFeMp6krMc852RU9zjYIV5MZjfoLoHMjZzl1yxCjXu+Dwx/QUjMlThCM6JUeSPieBUp6n28ExmOeJL+ZbBmD0945z9LksnS/bzhHtbo/dvgzFMjb34158nA7uwiIer40mGUPcP1yzia8q/8PMHxBO09suXTpXdfySkolYWfCWEKHR5HiWeRcO9+Gw6PZD2tQ9uVGza6UdbbK3+LoVf8u3yGRQv/mI5atUq8GSjG/Pe+H7Rary7R7XjCCe34cH2MmtyvrbDzmrWhoAeaQ1lHbvt3Z5GyQVJr8Wo+FvKlRRwu5r6sggsGc0SzWk1iWLwwl760Y1Jv77dTJFePlTUbQGEECNexMdmadh2ZW16lpVcra/EWOTzRdQpf183jWWuvo+de40P1LseDtt9R+UXco7Vb7rSWHARHw8Q3QC94op24tefaFPhbZmiXOjTJBKK/+Yl8jAFiR6YinqGAJCszFpLV29miw1JsCa1ChIeaeRYRvcoxdtQR+KIVDxTKWFLzmHc=
  template:
    metadata:
      name: postgres-tunnel-ssh-key
      namespace: postgres-tunnel
