---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-tunnel-ssh-key
  namespace: postgres-tunnel
spec:
  encryptedData:
    id_rsa: AgBBThtpi7dx8XFpLXxl5BYeSs4o+Z21d7TbJxHCU7wbFzSkhXQ9avHS2RO9D/345d4aoiDrj2xiet8oTKeJAzbrThw8ftXchxwfZGtnmLG0irXun5LyXbVfkRfMcQr8tpqcIVGo7epLP7OX/Dv5EkMHDUnqQGgH1CVmDat0SZDJUC35jQd5WtdSL2V+hDzDlf4bOh8Br7XmNakg4Mb1CegYe+R/L5drUQgcgQknczv4C++Pb2KtsixLrJzrLkKhvlzWFScE/yv7qdoLqz/YX4y8eki5ab28ItOdEGJvbh/OMRfr517cjqCnFPjWPJwOYwtDELx+wqm/dReligQBICK0AKWFnQqy/Wp2PBez9vvRR/b6iZkx+e8i7f0UeTEW4X5lcaYPaA/Q2LU/EzaZEu8MRnZMXp3v090b4RuNNjgzqn+W6sFqFzg2dp/II3XkUcyWzxj82uKNmRCZT1HB5k6IqyqxodLxequ+vhi+rmtTvJ01J1Ycsko8DCFV/z3StjZlck+bw/YOezTCTKLlxCETRhGjR2L2AFtyQeHGrVPzllU/VUMxuuM3wjz+bqv6U3VpFnH/CCQdjHQWW2xe3WcmzITWbhnyB/6TJIYA32qyb0QCJnMH0bW7xIijWxrKaxDolyW/aNJllRykL4gcQGnSSd+590PBwiE13wzaRcwpfn834bMSx+axeV19QB4zrVg=
  template:
    metadata:
      name: postgres-tunnel-ssh-key
      namespace: postgres-tunnel
