apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nowchess
resources:
- ../base
- ingress.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: nowchess-env-config
    data:
      QUARKUS_PROFILE: deployed
      CORS_ORIGINS: http://141.37.74.142
      NOWCHESS_COORDINATOR_ENABLED: "false"
      REDIS_PREFIX: nowchess
      QUARKUS_LOG_LEVEL: "WARN"
  target:
    kind: ConfigMap
    name: nowchess-env-config
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: nowchess-frontend-env-config
    data:
      API_URL: "http://141.37.74.142"
      WEBSOCKET_URL: "ws://141.37.74.142"
  target:
    kind: ConfigMap
    name: nowchess-frontend-env-config
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    metadata:
      name: nowchess-official-bots
    spec:
      template:
        spec:
          containers:
            - name: nowchess-official-bots
              env:
                - name: TOURNAMENT_SERVER_URL
                  value: http://141.37.123.132:8086
                - name: TOURNAMENT_BOT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: ncs-tournament-bot-secret
                      key: TOURNAMENT_BOT_TOKEN
  target:
    kind: Rollout
    name: nowchess-official-bots
images:
- name: ghcr.io/now-chess/now-chess-systems/account
  newTag: 0.25.0-x86_v2
- name: ghcr.io/now-chess/now-chess-systems/analysis
  newTag: 0.1.0-x86_v2
- name: ghcr.io/now-chess/now-chess-systems/bot-platform
  newTag: 0.12.0-x86_v2
- name: ghcr.io/now-chess/now-chess-systems/coordinator
  newTag: 0.32.0-x86_v2
- name: ghcr.io/now-chess/now-chess-systems/core
  newTag: 0.53.0-x86_v2
- name: ghcr.io/now-chess/now-chess-systems/frontend
  newTag: 0.4.4-x86_v2
- name: ghcr.io/now-chess/now-chess-systems/io
  newTag: 0.23.0-x86_v2
- name: ghcr.io/now-chess/now-chess-systems/official-bots
  newTag: 0.21.0-x86_v2
- name: ghcr.io/now-chess/now-chess-systems/rule
  newTag: 0.18.0-x86_v2
- name: ghcr.io/now-chess/now-chess-systems/store
  newTag: 0.24.0-x86_v2
- name: ghcr.io/now-chess/now-chess-systems/tournament
  newTag: 0.4.0-x86_v2
- name: ghcr.io/now-chess/now-chess-systems/ws
  newTag: 0.17.0-x86_v2
