apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: nowchess-kargo
spec:
  promotionPolicies:
    - autoPromotionEnabled: true
      stageSelector:
        name: regex:^staging|eu-central-1-prod|htwg-1-prod$
