apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-tunnel
spec:
  type: ClusterIP
  selector:
    app: postgres-tunnel
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
