---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: nowchess-staging
spec:
  encryptedData:
    .dockerconfigjson: AgBBA1306BUYWtBtTYNrDSzfQPO5AYgaDYNEnDJz10QcSVxEK1MAMUiuxM1JBZT7Ba3lyKWwI8XTsVEYcIoOw1UoQrlMrFsEmykF5BBLY54cRgAw60wyZ7iyG9G00CwqBXCMtXSMNFJnIyUwpY3gAEN8eXx27IpaekHiwuN2p91pHL8QzA8SbUx3kkN+5AQVp2IuqLXNVRp8KiQdO/3WnlbbYdNGAI8jxXQnHt4Wig8Wl4LlBUDVGc+cvPTVutNhqPjg6i1Qz7dswTGcZqYS2H4F+xrCATw571+dQPh+A7gZDmADENFwncbuOkwqoGsvZ9fkpyLhcc3TQ36pVc13nVlJt6N235MgKtt3WxatAwQSIHCXecVPu591DbLIjb1MzQpoGfKEznCJHAuoQpXpsL8vKTFm1+fycbwn0rtdQapC3+xP/RqEwUhwhgsxcWx26qaZ/q5lgt9UFcsWSPXgUIllTV8BqHkdEa4CgftxB7smQfNNfGhCOu4a3Gpg25YwOnmQHmDuId27wXzu1Mut86sxvMCuuUwd2Fz9MP7/weN46S1Zoc4soBunO0dUWmVysTyvLWFarjHbliM+v7X2SWBajj0rGv0lLXALEmxeA0jl7/c2RIWZ+hMM3KjW0FnzlzNExvwsCc3Mtkv73VUe7xQVKfR4N/FuKRNyXR1lSS0uzU+Gj6Gcfu6+F/jWcooKWGqPcVRSUtlPryyPOX59iy0f61a65K35MlHCzZGC8xZfX0DGwITTttCivhc56CRvV5S/LZ4vYus/nbLCcVv6ty2n0Y15usUkHlAVAdWPEWMef+iGaU3LUy02bXMLfGEIcPzXjG9F2RGDIHsDpdfWBj4lbQxNfofZrQYFlgrV+s6EfVE+NrWrUgygb1ck70fSHxg1/f5B58x/f9ipJDhCa5uG5gjVoZ1zlS1NBlxbnbcKaJDK
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: nowchess-staging
    type: kubernetes.io/dockerconfigjson
