---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: nowchess-staging
spec:
  encryptedData:
    .dockerconfigjson: AgBLRFtY/eodbVGQTdJgbADQlE8ogw5WFUXeyRI0OQSlCeW8JRcu5hXelvdtKnx5I1pVevF6enzenmwBL5HJn/iU1yAX+b6Kx/BsaCFRA+/vYEugpAzRrv5qBUBHCV9jkTV0NqhQqFmasp2jErMLtw6ZWnP1lsr6cdEYZcEVwe6wZG+dHlfXTvxaDOt0bjHRFDNM+a0NTvtg33ybqPx+nw9XwC4a/O+afD2y5HokchFaGlC8aYJDC3MuAQc9/JgSG1++xosop5XlH4GLsm2xiBbczzwODtGBDcH6DWmRhUyyGmEC1JXJf7GywTlcRkYiYRpDth5aCKMs9wyZx/5cCxyhflj33pC2lFd4DdFGYgFjLF5xhXgu8Ud8Uhniq3R6buCEn1qwCrFJgpweqmzSozswDNk1pNOrlWpHBNmpiHDYRWt+TsSIac8sD0zyuDc7OaINDFBXYZ0sOfxsgG9mxjq6ICG3QlgTdsVJW6UmJfVmnu6jme5nVTOKEtMhQaPfvnPEdQvy15nittM7K5fqfLOUDUnYg8bSbCd3FZZIL6oT5xOnwAvYvzTYjadT2FhHKNNvzUTI4i/8Dhser6b/JNqbIwZy9JcQZ9XAzNEgLyDwGaetnfcc4ZbgRrdXQEsKvxBGFwKL+wpSG3cLz5MkjY6M9Scg9ztHYYR1wv9tVlS+efHrOiSrRfG7VaInXrJT8hY=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: nowchess-staging
    type: kubernetes.io/dockerconfigjson
