---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ncs-internal-secret
  namespace: nowchess-staging
spec:
  encryptedData:
    INTERNAL_SECRET: AgBiCYSekI3NED8XUXKmM0F4y1Od9ksWi+6acq93bfy7s5mKeIfKCRhnzKD2Mjc5fu9Zfwo/aMp6dsdoLmmyiCqbRJMGM/RK5VtRa4pFxcrqoEoHAElFbTt8BgQno7Tf4HZckbVgTIsXWcEVgfwUMuSg815g0R8kiwbcw74Bh+1uNmETcPGgVaUJdKMRNt998UjiU/JIwp/MtCu/IU0hrhi7+s6F3Ejzl79vhbeXUDE8qX8FOAt+OCNan4fKi+ac8nw8r1gRB3b0+U+F9O0KIbPTO3BStr7DeRPex2KRlFuvGcXdKuOchlqPMZkIKIcwnT/ePHzsMxRBvYEAoZubUya+Dk3G3oBbZow0yE84Cg9rjgv42nxY15r+BFg/MM936UHfbAB8tCGYfsruoD41HcPM5cOzU4gWVadKaevlwN7f99Xu0lzXWvxjCl8yJCzNn10+9ZQD0nuX5Dl56mKqwkoAwLd45MQbJreVudmoTcJLPs5R+H5+tlC+mrxoJkNmojpl2a4EifzhigNd2XX94wvy6pAkhoDiWqxDF2mtj7bskOy32X7uKDD3CtjRZohLfUxRaKUQ6s7nV0x4yzaD5gP6KIsiZjqoF8yiImdQYN+OdbCMwB4VeYY5GdBGsCxjqp20iL4UGVnwHVLX8tC2tvoetyznkW8tOEpQ6kcBkgxddjCTF5HTLlHRvHD0du6hUTlVHKa4Jo5zhrejjM3F9/D1f+zvrw==
  template:
    metadata:
      name: ncs-internal-secret
      namespace: nowchess-staging
    type: Opaque
