---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: nowchess-kargo
spec:
  encryptedData:
    webhook: AgClNCNYBsDf98gqK1llO81ISh+3j9F1R0585ZMH0wG/WZkX9x9QO6Fm7gMfVlGH1u1YfI6DLVC78z9y94LAyHCXuL6BtBckgMg084FqMjx2hPFtKMj+zvLFGysb5pgkFjm+OmCi06Rc9UZ87Vd24/o8U/YkeEA4K86Ohjun/rQzjh+KGTTsLVoy1T7vT256HbKpJ/lK3Jc0CIzSb7bfEBBHlQiHHlxRYRrlw3y1HLKzU/1Bdr1eD34UvcsCN7kDhsxmx2eo0MY44AjerPjGZG0SpS7Akoj/1WZn7m4k1l22ND493QLSh/ZkXaT+SJQOMgmjmSF+xu63IMVH2XKFhq1DzkeQxzBOQftAx8yifd5GMbnu7eyJ/5j4UkqIAlW+O8SPk+HURS0vcLK+Hw3NhEBqOGfePJ71MSUvFHw+6JJn8oH8DKY3F2XHPVvwuEnODZAZ9XVoqbMTWtQqQ91Pm95TMkMgEtUIogfvEYDr6qTt2DrEjefv4CIV9yATKjojELNlj7umFsp2ULkXBszuaJhkkp5gl0TxEiTP1756fR8r5bAZIqGDiaBtMr3mjBga7jSEQ8pKb78WnKaA0A2XVqxZFm4w9h3CeeGQ+WIXnftkkRyIJ0PNfB7pFTXQAkVd3CGMtlSrrzsSfhSuhStQ6bvqpUQsa5fTfDRVkvHUvYjsMoGjSUBLQPtF3+rfCEK0usxOcIW9ZZT+IWYu7BXQ7FSNNqscYYwQsLmwf+bKtwB62qk3VfZ1B92P5uxR16k09gCgEhN9q4p6Qs3KNgWEjprbUazAez5kKbYRc8kenwwtgjdnjJ1TTpsp+DhEUtxh4X4Y5IWgzd4xLBy9Nnq/H9eBY2k62a5Sh1oP
  template:
    metadata:
      name: discord-webhook
      namespace: nowchess-kargo
    type: Opaque
