---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kargo-admin-password
  namespace: kube-devops
spec:
  encryptedData:
    ADMIN_ACCOUNT_PASSWORD_HASH: AgAS2UuCreUX5FTCQT0dRkP+dvIFUjtRjNbVKdPuccTOK9zgGltEmKFTA2lmlD3yyktCMcVBoZNeMui7gfBHIA1DlixZAlQmG4GYbEUN7xV3JClJh6WMUiTsY/NubqAW6mfRY9K9msE7LGGPRqFOiMO2zgZwJg6wF6LynibFZUltooEY2MOwbgUHRevKefKZgxNBJqPhLAUPTggyDQpQaKEAxJAId9Dt6Yqy3JtO7OsylXQUpojpBnaFsTC2UsidVac42/RR4pu0E2zd8Xr9bR8Vb8UBlsSDPWzcUaZrE9e88WkhhQuxlOYuZ0L+XX+x9KdrMv5vcShtbLqC+TQ9ZVT+G9NOzr1B3RX7wf0RphkJDNUcBPmamacmWguBM4lB5tIShifoz4nc7Sj56Bl10tbpro6VEAjdoVEPn7GoiKgGXES+jx62g47pIWX+WYuB685/5j76U0bCbjrddYjLCDtO598CDoloEgxku+et8vy1Xbup0PlkuHHwy+prg56TkKuQM18UTD8DCZbgpicHZxCtgL5dhlt9ep578som3t3JOKok0fKv/KjSINykrbSNRCyjefi64JkloBHx9fKKW6lUZY6NyaXUWrYkPMlWk7RrRr+Z0YTmELWlfkgysP/U61znYZlJL9Rqakbm2wsdO9L6eHWRcqqyHJguOo/3Cj8xAi03XFOc/H+nU63mKd9+MrgO95HeJX3ToiF39jT1CYI7r7lhNqRYd5g0QJKOZlwooQcEP6AuJFG8vP32fU5vX/VTa2XwKOgL7qxN+1A=
    ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: AgAB7QxyL6Cl+7lcUVaSTx06BtsvSVjEhTEtL1ZyQgeI5E5sAeQn4EHHzlP1J8wVIiugWJu1H5W15vTGMrZz8g0OyFbMplx3qz6oEZc8IqBf6M2jtyfcNvlfWYU3V6HF1K0LK/+9H5RDEXPozBBmpaqazv40jXfAnAt2xXtYDVpW3+V36L2lZgThCbO/iDMv8XfE9/y9s8hJXW2x/WTHJKtoDiT1Mbl9HqXv86Si1oZMbcgbyxt4WNC8NkYSH0n8nubMyNJ1Ji1nrJntqUCccUxxb5f0Te8oRgQvbuqzLzJ/bxRfRnjPsaO64sZWIsZhDqspDktezTmo6dA8NmLRHVhwT/hjN5JtG7aZ+sGqng7Ye9RJbRa+zxJcT9CHO7pPrigNam8OxHumAMabNItVHzI1zyV4ggq5HBVCSr2F9jor+j1mnjHqOAH9Mij2owm5ObYfPMKRZeMtDJIHNCYLsfrKHIjh1v8/XTjkHQMpp2QN/+yDVEW78XVSC60Orupxhg261y6GQrpGRCtSppRd5OdmevyDNl9bwdDPWXT9vG4qBPE6INrulLc16ciGM9yqOLlar86IVxbKgPEcT4beuHPW7N+8qrVhcsWHM1BNyJx84B2PsWXSYAb95alZdJAyKDVq/zdRDbrHjHsnEQm6ybMbrKPvO+WxaIs1IbLDbHsUK8d5LW0i5EYLuHITvQ67eAgqa5EdY8JG8cf4+qJHiDkrm6/4/brJBELv/Zrpj4Lo7w==
  template:
    metadata:
      name: kargo-admin-password
      namespace: kube-devops
    type: Opaque
