apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-tunnel/secret.yaml
  - gitea/argocd-gitops-repo-secret.yaml
  - gitea/gitea-gitops-secret.yaml
  - kargo/kargo-admin-password-secret.yaml
  - github/git-kargo-secret.yaml
  - github/git-nowchess-secret.yaml
  - github/git-pull-secret.yaml
  - nowchess/staging/ghcr-pull-secret.yaml
  - nowchess/staging/ncs-jwt-keys.yaml
  - nowchess/staging/ncs-db-secrets.yaml
  - nowchess/staging/ncs-internal-secret.yaml
  - nowchess/prod/ghcr-pull-secret.yaml
  - nowchess/prod/ncs-jwt-keys.yaml
  - nowchess/prod/ncs-db-secrets.yaml
  - nowchess/prod/ncs-internal-secret.yaml
  - nowchess/kargo/git-secret.yaml
  - nowchess/kargo/gitea-secret.yaml
