---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: nowchess
spec:
  encryptedData:
    .dockerconfigjson: AgBXVpmDi8F4GQNI4+khIPrT3MZRviD9X8o/zkxKTWDSl/vFw15xPATyIIlWoomzXHszjmNdta0OlqXsYqfK738BKfRnW5eLzsGquoEijj2w6D0yCzJraJlF3IobmX975ZW2JWUDtcdrHZOCNta1/sHxOBL5pjTg/ePfThU+/Fs/rTOZXleh8lmRiAd1PNRaxN7k87gOJA1G1HzY/0EQjaJ0EOE9SOPQQufclXJnbaYgvg9H9k9fRt87fFkeDESPZAhMzDY5L0Bke1FSD/8g34S94dJReSzwbAhrK9B5b0ZIVXFM72zSWRdbpTRcVhWOq1fBaZpfvWdiE+rhxADcbl8j1jXvU0LDtyAQkYKP+0by2XXzxiX2ZTxw7SxWYkYlfxcXHsmAvreGZelWtgTrFv4IeW2+H7occWzNW3t24axBavMAERYbEFYkdMurJjYNxocSf1tKc+hHeQs/XHj06Oj8ZJmu/wPpD/wipHMkgJ5JH3dUCDTX3s+kqoF9wcA9Pj2A6SbqlSHLr7vIYEAoIVXuq6IkZ+L9/DR9QQxEDrCgBU7Y8gOJXqzE+LGROHvo3ZEzYuvJGVsAVH5BwR97b6GBoI0nR5aMnZQtMGqRGGZIUWqG+wIn124Sd4Y/lQ8akmKMUSf/xnfG3Siv+qUpElE1UUW/Z1frROq/pC6pHBWSvhZaSbnNqiyWRh01Dc0ffUmIIbQiFqylGk54T4TiTm+8jVjTP8FihocjDdK+qNLp1tV27MnY7nPhNe642bVZ63ojzP8CcLQmCzrSA1NaauHrsT5X8LYKP02rH63BU+jULhML9XTi++cM/vbWL6cPtn6PvjFwfroXnjbiTihq108IGHjmIQctCyatgx2P35MaRIhU6K7t/mVF8pUMMNRO9GParIeWuhRv8NDPBvQl1SCSfGqmLW5KsUdOeCcushR+Jgzr
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: nowchess
    type: kubernetes.io/dockerconfigjson
