---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: nowchess
spec:
  encryptedData:
    .dockerconfigjson: AgB4sOxs+upY0FewOJpaO0J1pOrr0BuBZsp/gNNgXJUeuOduIIpzDoU9oP25E0AjBcpeDmq32278S0uHlOG2ZacBk78u/YuKkSl13dTSJ1cEQ5v+SD6SzyLI0USWFxZtT32Jov98Mntg2YDDU4IP1NDVO4Jj/p1HYORkTzmTtD25dMLR8FmcDR9r1+EYDpFV4DkESXKZYV28Ddank08tTevAeGtsqB4tdLcJTEydzg4qw1uNZ11E7TwWqiBwGveuXN/EPsmojnLOJdzPPeFkJfp3N7z4GHWIBCeOrOqGCl4mez4Vri7ixDbsFkMKRJiT40cSkaRKRHGky9HC3kc6a81gzK/FZXBS7Z/fBEJSdfKTu1GOJYP3YknEjkdrY5/neK29L6Wb/4MPN4pTjRdAIigspTL4qCRIF4vZYWO1Z9NCwObnVMMSsL4Jh45V918XvtjF9kuyUUTLpBPyzlTbFGP9f54Zvq09snkvbwNLptrmxnHNXICfYLtFCBETdUc7x7yuC+yEIKohq6YTZbShrnWioHCwtwf1XETBWmWOTo7l9Aq9VIlyR5FhPZ4A4ZoRQOoDkdIhOt3yyn8wc4UXuIBKk8a6SUO43lQ0DGkLdAprOoPqVXxtYntdmgVLj2FjfTuh4NCLCkOs4VcvlPtVbBUkAfByNnRWknT/4qfciwwc1xhcAoMLMJYqk1Iedf4x0vk=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: nowchess
    type: kubernetes.io/dockerconfigjson
