---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ncs-internal-secret
  namespace: nowchess
spec:
  encryptedData:
    INTERNAL_SECRET: AgAUyYV3ZW0nqHhSwno6fctuLxZ7f1Qu4KUS0o20+HGAPTPENCfmPqIn6qVuzxUwRZcbyZhXQXCbgBVgMRKGnAO87tfDzNBim/fKaz6nGzetwUyg/E6lgOmRolZ0kcWX19psFzBv6Uzw6DvYwrSmmeTNkmuiN/uOLs2Jbb5gAHFhqpxJxLtB1PG4NI76bl/tg8rONuVMuHPRQowiNUfyLeKEGbjvYpVdNZu/lJXzaIuDjKVftQ61z8tGaggFbU2mnx3BR2WcwcvTO29P05hAvPEammSih/ciVE+kHDcCecKANXGQNmGUXrYnXly59Vdf2LcE9/zMcG6mB8qq3V6fSd+phUgJu8Qwn8KlyO0p3A1rLpyTVvpwVfKlqI7O4rKBAaIjDUPsFPUWLvZbx4nPwocU8M8v6WTqMpgxLkr2n8LuLHhehml0kMcCPlZl8EzyLeV90gRNQSNbGNQeKxpiwuHEQsbiUZEH1EziL418ZtOjfVwX/S/xqOpOKM3sdXbFGcr01xRn23gfxSKm0I26ob9ANaNGGHZTIt0h6VHNXpGHCZJ2FJNUWqabQaO2rHt6PBu+3c9jofV1GwgqMU2bcNgbHdGNwKSGwhrIuUpy7uMX6ppqPMWBcITb+fGTF63ISIYTBD47o0hGisef39FeuErW+62udZ9hyw1fZkkveAoxdPMb0/Dc6s5I/mZb2s8kINAKlof1pa6L+xgZ6gqxcPKlvyFaLRE8dfrrBJHBbPC+Hw==
  template:
    metadata:
      name: ncs-internal-secret
      namespace: nowchess
    type: Opaque
